const W={"läxa":1,"diagnos":1.5,"inlämning":2,"prov":3,"muntlig":4,"NP":5,"lov":0,"studiedag":0,"utvecklingssamtal":0,"praktik":0,"annat":0};
const LBL={"läxa":"LÄXA","diagnos":"FÖRHÖR","inlämning":"INLÄMNING","prov":"PROV","muntlig":"MUNTLIGT","NP":"NATIONELLT PROV","lov":"LOV","studiedag":"STUDIEDAG","utvecklingssamtal":"SAMTAL","praktik":"PRAO","annat":"INFO"};
const COL={"läxa":"var(--lax)","diagnos":"var(--lax)","inlämning":"var(--inl)","prov":"var(--prov)","muntlig":"var(--muntlig)","NP":"var(--np)","lov":"var(--lov)","studiedag":"var(--info)","utvecklingssamtal":"var(--info)","praktik":"var(--info)","annat":"var(--info)"};
const DAY=["söndag","måndag","tisdag","onsdag","torsdag","fredag","lördag"];
const MON=["jan","feb","mar","apr","maj","jun","jul","aug","sep","okt","nov","dec"];

const MATLIB={
"G|2026-10-06|Matematik":{desc:"Bråk, decimalform, potenser och tiopotenser",nPages:42,nSheets:22,nFilms:6,nWeeks:8,links:[["Matematik Y inläst, s. 8–49","https://inlasta.ilteducation.se/books/YLGQXJTFrOO5Rp6k0b6Qp"],["Arbetsblad 01–83 med facit (PDF)","https://www.matematikxyz.com/larare/ewExternalFiles/Y%20AB%2001-83%20med%20facit%20i%20slutet%20v-4.pdf"],["Genomgångsfilmer, spellista","https://www.youtube.com/watch?v=nLCrss0TQD8&list=PLsoSX3GymcNFCqZVXj5naVrwkpsrg3U2O&index=34"],["Presentation: Vad är ett bråk?","https://docs.google.com/presentation/d/1-li4x_VR-A9cZuNbiGOHVNuJXyLqZUEzEFVh2fWTEqQ/edit"]]},
"G|2026-11-17|Matematik":{desc:"Procent: andelen, förändringar, det hela, ränta",nPages:37,nSheets:16,nFilms:5,nWeeks:7,links:[["Matematik Y inläst, s. 60–96","https://inlasta.ilteducation.se/books/YLGQXJTFrOO5Rp6k0b6Qp"],["2.1 Andelen (film)","https://www.youtube.com/watch?v=yjE-97Wduws"],["2.2 Jämförelse och förändringar (film)","https://www.youtube.com/watch?v=R5FVC_bSuqE"],["2.5 Ränta (film)","https://www.youtube.com/watch?v=vf53gQXFDyM"],["Arbetsblad 23–38 (PDF)","https://www.matematikxyz.com/larare/ewExternalFiles/Y%20AB%2001-83%20med%20facit%20i%20slutet%20v-4.pdf"]]},
"G|2027-01-18|Matematik":{desc:"Geometri: omkrets, area, volym, cylinder, kon, klot",nPages:39,nSheets:11,nFilms:5,nWeeks:9,links:[["Matematik Y inläst, s. 106–149","https://inlasta.ilteducation.se/books/YLGQXJTFrOO5Rp6k0b6Qp"],["3.1 Omkrets och area (film)","https://www.youtube.com/watch?v=ISTwM1XQg80"],["3.3 Volym och begränsningsarea (film)","https://www.youtube.com/watch?v=KVj8_EXP5vs"],["3.6 Cylinder, kon och klot (film)","https://www.youtube.com/watch?v=Ucm-OxlWANc"],["Arbetsblad 39–51 (PDF)","https://www.matematikxyz.com/larare/ewExternalFiles/Y%20AB%2001-83%20med%20facit%20i%20slutet%20v-4.pdf"]]},
"G|2026-09-29|SO":{desc:"Demokrati, ideologier, Sveriges styre, val",nPages:0,nSheets:0,nFilms:11,nWeeks:7,links:[["Provplan SO","https://docs.google.com/document/d/1PZZEpCV24wuIiB9HW60wrZexeepzvg7Dmv1Zkrsx5-U/edit"],["Arbetsuppgifter (samlingsdokument)","https://docs.google.com/document/d/1qMSaxbJV6I57YY3pBaoIdvZI-Vmd8bp78bfzvXuSv-g/edit"],["PP: Sveriges statsskick","https://docs.google.com/presentation/d/1HvPNwl7FtvmECgk6VB7YS8Z1VvaUBnjYjxe2Ad5FImc/edit"],["Begreppa: politiska system (filmer)","https://app.begreppa.se/videos/samhallskunskap/politiska-system"],["URplay: Ideologierna (filmserie)","https://urplay.se/serie/227244-ideologierna"]]},
"G|2026-09-28|Engelska":{desc:"The Media: lyssna, läsa, grammatik, kort skrivuppgift",nPages:22,nSheets:0,nFilms:2,nWeeks:7,links:[["The Death of a Tramp (text)","https://docs.google.com/document/d/1CvkUbY0pbcbsuml-5bapZe-YmM1XgXye0p6gg2G2hW4/edit"],["Work with words / questions","https://docs.google.com/document/d/1EHBFKy-30rEfiZVbQU_xcXSikOc9wCJAmOqCFZ71HAM/edit"],["Mind the Gap (kortfilm)","https://www.youtube.com/watch?v=hysDoq6BH8U"],["The Bride who vanished (text)","https://drive.google.com/file/d/10OQG9fu5XSqalAKAl3FGMAmRdOxVH2gX/view"]]},
"G|2026-11-09|Engelska":{desc:"Muntlig gruppdiskussion om kortfilmer",nPages:0,nSheets:0,nFilms:5,nWeeks:4,links:[["Short films (arbetsdokument)","https://docs.google.com/document/d/1xJnZAOulmORQXeslC5aBW7utxl4OiZ9TyFvz7Pb8eRM/edit"],["Discussion questions","https://docs.google.com/document/d/18nVkfPJo01d2D5MB8eO9aKR6uI051yVw6htHAmq4jTE/edit"]]},
"G|2026-11-27|Engelska":{desc:"Recension av vald novell, skriftlig och inspelad",nPages:0,nSheets:0,nFilms:0,nWeeks:4,links:[["Short story review (instruktion)","https://docs.google.com/document/d/1FiJtggMpwvqLzm9q8uJOVWo4npiIwniEoGl8U53EYYc/edit"],["Lamb to the Slaughter","https://4.files.edl.io/4a65/10/23/18/235824-cd055462-e062-467c-a8ae-492f46d8caad.pdf"],["The Sniper","https://docs.google.com/document/d/1l1Ocz6c7SXYRnUjslGQxMCn_rieDC1gYvyIPWdp4saE/edit"],["The Hitchhiker","http://www.rodtaylorsite.com/media/dahl_hitch-hiker.pdf"],["All Summer in a Day","https://www.stcypriansprimaryacademy.co.uk/wp-content/uploads/2021/01/All-Summer-in-a-Day-by-Ray-Bradbury.pdf"]]},
"G|2026-10-01|Kemi":{desc:"Organisk kemi: kolatomen, kolväten, alkoholer, syror, estrar",nPages:41,nSheets:0,nFilms:6,nWeeks:7,links:[["Inläst läromedel, s. 101–141","https://inlasta.ilteducation.se/books/l5TBYPC9lTY82iI2QzlC0"],["Begreppa: Den fantastiska kolatomen","https://app.begreppa.se/videos/kemi/organisk-kemi/den-fantastiska-kolatomen"],["Begreppa: Kolväten","https://app.begreppa.se/videos/kemi/organisk-kemi/kolvaten"],["Ämnesbegrepp (dokument)","https://docs.google.com/document/d/1Lq-DTTthLlUX3CrVQecs2664_YNlIXZHoN_nMD0zQ90/edit"],["Quizlet: Organisk kemi","https://quizlet.com/se/254407874/organisk-kemi-1-flash-cards/"]]},
"G|2026-11-12|Kemi":{desc:"Matens kemi ur Läsbok BLÅ",nPages:0,nSheets:0,nFilms:0,nWeeks:6,links:[["Läsbok BLÅ (Polylino)","https://app.polylino.se/books/rj9LE761tAGtjUrL6PUlq?pl=sv"],["Elevspel: Matens kemi","https://www.elevspel.se/amnen/kemi/4173-matens-kemi.html"]]},
"G|2027-01-14|Kemi":{desc:"Repetition organisk kemi",nPages:41,nSheets:0,nFilms:6,nWeeks:6,links:[["Inläst läromedel, s. 101–141","https://inlasta.ilteducation.se/books/l5TBYPC9lTY82iI2QzlC0"],["Begreppa: Namnge organiska föreningar","https://app.begreppa.se/videos/kemi/organisk-kemi/hur-namnger-man-organiska-foreningar"],["Begreppa: Kolatomens kretslopp","https://app.begreppa.se/videos/kemi/kolatomens-kretslopp-och-vaxthuseffekten/kolatomens-kretslopp"],["Elevspel: Organisk kemi","https://www.elevspel.se/amnen/kemi/781-organisk-kemi.html"]]},
"G|2026-10-16|Franska":{desc:"Kap 1a–1b: glosor, prepositioner, negationer, vägbeskrivning",nPages:27,nSheets:1,nFilms:5,nWeeks:8,links:[["Övningsmästaren: ljud och övningar","https://www.ovningsmastaren.se/book/c370dd99-6970-43f4-a16d-350e086b5edb"],["Sammanfattning kapitel 1b","https://docs.google.com/document/d/1AtEvCH7V721MS6SUsAZ_MNpd3M7OcMNqxkjwmBusz0A/edit"],["Fransk grammatik (presentation)","https://docs.google.com/presentation/d/1lejfW11sPqwFEOxG0bYZggI0eKCz3hHzHz4G909jaw8/edit"],["Alors grammaire: la négation (film)","https://urplay.se/program/217737-alors-grammaire-la-negation"],["Att beskriva vägen (film)","https://www.youtube.com/watch?v=OoFsERiWYsU"]]},
"G|2026-11-27|Franska":{desc:"Kap 2a/2c: Je t'aime, vouloir/pouvoir, demonstrativa pronomen",nPages:12,nSheets:0,nFilms:0,nWeeks:6,links:[["Övningsmästaren: ljud och övningar","https://www.ovningsmastaren.se/book/c370dd99-6970-43f4-a16d-350e086b5edb"],["Fransk grammatik (presentation)","https://docs.google.com/presentation/d/1lejfW11sPqwFEOxG0bYZggI0eKCz3hHzHz4G909jaw8/edit"]]},
"G|2026-09-10|Svenska":{desc:"Faktatext om en uppfinning, kopplad till upplysningen",nPages:0,nSheets:0,nFilms:3,nWeeks:3,links:[["Genomgång: Faktatext","https://docs.google.com/presentation/d/1IvKh-LEAQndGggNkMTDsUQ64taIkMrPwZAH59YwYxMo/edit"],["URplay: Fatta historia – Upplysningen","https://urplay.se/program/207592-fatta-historia-upplysningen"],["Texter litteraturhistoria åk 8 (PDF)","https://drive.google.com/file/d/11flgUqKfd-tW2owU_MvgxMbENGaDg6V4/view"]]},
"G|2026-09-29|Svenska":{desc:"Språkhistoria: fornnordiska, dialekter, lånord",nPages:0,nSheets:0,nFilms:0,nWeeks:3,links:[["Dialekter och språkhistoria","https://docs.google.com/document/d/1bIL9PHPIlWCjFuWDyGTQgMS15Jk1_LXrY4lnbNtmGSE/edit"]]},
"G|2026-10-23|Svenska":{desc:"Presentera en novellhändelse i nyhetsform",nPages:0,nSheets:0,nFilms:0,nWeeks:3,links:[["Litteraturhistoria: Renässansen–Romantiken","https://docs.google.com/presentation/d/1jFZcR-GnBpxaRbYN6jGMOFWV5At5ousNl4xRJ4ZVsHc/edit"]]},
"G|2026-09-08|Textilslöjd":{desc:"Batikfärgning och skriftlig materialredovisning",nPages:0,nSheets:0,nFilms:0,nWeeks:3,links:[["Uppgift: skriva om ett material","https://docs.google.com/document/d/10t6Ehe_uNvWkiGiKMh7UmgdvVPHceRC83YhnD3O9rM0/edit"],["Slöjdlexikon","https://slojdlexikon.nu/"]]},
"G|2026-12-01|Textilslöjd":{desc:"Dokumentation av sömnadsarbete och återbruk",nPages:0,nSheets:0,nFilms:0,nWeeks:10,links:[["Sömnadsarbete/återbruk (uppgift)","https://docs.google.com/document/d/18Krt-6e227mXl2-RR9eCHL2Zg2tzZ2aTXY7gsZBKYK4/edit"],["Tips för slöjddokumentet","https://docs.google.com/document/d/1TsBDEfYlYq6j6ZrXTHnMux4nTcM7U_P8OjDHYffSmyc/edit"],["Vad en skiss ska innehålla","https://docs.google.com/document/d/1RmFxzfa6W_cfvIIUvk4ZKCnm97a0YuFNgJcp8WZ5Mc0/edit"]]},
"S|2026-10-16|Matematik":{desc:"Tal: bråk, negativa tal, potenser, grundpotensform, kvadratrötter",nPages:45,nSheets:2,nFilms:7,nWeeks:8,links:[["Film: Tal och beräkningar, s. 8–14","https://www.youtube.com/watch?v=ewJgndaV2h0"],["Film: Räkna med bråk, s. 15–19","https://www.youtube.com/watch?v=4eP3WlGM8ic"],["Film: Negativa tal, s. 24–26","https://www.youtube.com/watch?v=FrmizRbKPY0"],["Film: Potenser, s. 27–31","https://www.youtube.com/watch?v=iP9IvZhQ1ek"],["Film: Kvadratrötter, s. 43–49","https://www.youtube.com/watch?v=bVPCRNc6rEw"]]},
"S|2026-09-09|Kemi":{desc:"Grundbegrepp: atom, molekyl, joner, elektronskal",nPages:17,nSheets:3,nFilms:5,nWeeks:3,links:[["Läxa: begreppen vi gått igenom","https://docs.google.com/document/d/1ykFbvs9_nnRnYMIMgDSiFNQz5NbLdH7wo6Bevkr02ro/edit"],["Övning grundläggande begrepp","https://docs.google.com/document/d/1Dhisz-NPXhpZNlYF8r4lDm0D-ncDUvYhJlzdeNVcCck/edit"],["Film: Elektronskal","https://app.studi.se/l/elektronskal"],["Film: Snabbkoll joner","https://embed.ur.se/program/213565-snabbkoll-joner"]]},
"S|2026-09-16|Kemi":{desc:"Labprov: fällningstest, lågtest, jodtest, Trommers prov",nPages:0,nSheets:4,nFilms:3,nWeeks:5,links:[["Analysmetoder (PDF)","https://drive.google.com/file/d/1B3jLl5iNXRQXtOvvhb5txfEdOZDAgSWA/view"],["Fällningstest: identifiera okänt salt","https://docs.google.com/document/d/1VMDf7sEvQexrpH7RmAPL4Qdz8j27DNXdYPSFJP2E_Mw/edit"],["Lab 4: Lågtestet","https://docs.google.com/document/d/1ER1feejIjLrZ9pysznfLpSC2cwzSpt4_GlAM-vQE5IM/edit"],["Film: kemiskt detektivarbete","https://app.begreppa.se/begreppa/videos/kemi/blandningar-separation-och-analys/kemiskt-detektivarbete-del-1"]]},
"S|2026-09-25|Kemi":{desc:"Atomer, joner, bindningar, salter, analysmetoder",nPages:28,nSheets:8,nFilms:11,nWeeks:6,links:[["Provplan med sidhänvisningar","https://docs.google.com/document/d/1SkYJaZZLZ9vZuI2uCULiEAO95PjSi6llmy_qGkb0dws/edit"],["Övning grundläggande begrepp","https://docs.google.com/document/d/1Dhisz-NPXhpZNlYF8r4lDm0D-ncDUvYhJlzdeNVcCck/edit"],["Övning joner 2","https://docs.google.com/document/d/1zPVjZuoPJoHJeAjlCI8GK7KVHDZfBlb0XVl4Gj_9Lrw/edit"],["Film: Bindningar","https://sli.se/apps/sli/prodinfo.php?db=3&article=V4576"],["Balansera reaktioner (simulering)","https://phet.colorado.edu/in/simulations/balancing-chemical-equations"]]},
"S|2026-11-13|Kemi":{desc:"Elektrokemi: redox, korrosion, elektrolys, batterier, miljö",nPages:22,nSheets:6,nFilms:8,nWeeks:5,links:[["Provplan med sidhänvisningar","https://docs.google.com/document/d/1JuzSKP2awjI5UXoJD1-SGiGOhiH9LPSDdXUdak3UAYs/edit"],["Provplan + instuderingsfrågor","https://docs.google.com/document/d/1Aiar7ZYrRGzw4cB45vnh_YUfLxpnKhEBMdalro-boxk/edit"],["Elektrokemi ur Kemi Direkt (PDF)","https://drive.google.com/file/d/1kfo6OwruAQuy5gjYLr4uuxp9TPHM6zO0/view"],["Frågor elektrokemi","https://docs.google.com/document/d/16dr2yRZqeyNuHQQKTt6ri2Nk6LjJb_tvxa4DofdIdp8/edit"],["Film: elektrokemi","https://www.youtube.com/watch?v=QY-L8JLjQC4"]]},
"S|2026-09-15|HKK":{desc:"Eget recept inom budget med kostnadsberäkning",nPages:0,nSheets:1,nFilms:0,nWeeks:2,links:[["Uppgift: Budgetkocken","https://docs.google.com/document/d/12AGcs1Dwlur0ePCwVZ8dr1fmqSc2KSBH-8WXveBSNF8/edit"]]},
"S|2026-09-29|HKK":{desc:"Privatekonomi: inkomster, ränta, försäkringar, konsumenträtt",nPages:36,nSheets:8,nFilms:2,nWeeks:6,links:[["Genomgång privatekonomi, del 1–4","https://docs.google.com/presentation/d/1s4pm4yoQLuXTVaOidej1GdaW6V_5raYlHLCiReXFd8E/edit"],["Uppgift: Betala en faktura","https://docs.google.com/document/d/1OLLBLUpJxu5kFFxUXf5-AjYgSmmy97acuhkCHCe2s7Y/edit"],["Uppgift: Försäkringsdetektiven","https://docs.google.com/document/d/1NBQ7qJvdYqOzfHIG00ufLqrUo1yeLyzn4noaoMkWLew/edit"],["Uppgift: Dina rättigheter som konsument","https://docs.google.com/document/d/13eMNdpHUqtcjrDI93E22teJLTk36tnG2yASePm3lMPo/edit"]]},
"S|2026-09-18|Svenska/SVA":{desc:"Sammanfattning och referat med källhänvisning",nPages:9,nSheets:2,nFilms:3,nWeeks:4,links:[["Häfte: Sammanfattning & referat, s. 147–155","https://drive.google.com/file/d/10uQNNvNwgyiEQvI-dkUtsBQvotG--UaM/view"],["Genomgång: referat och källhänvisning","https://docs.google.com/presentation/d/1wtvywMYXtjBJp58zbGTlvamJxZsHjZZNgZOfa_Jchdw/edit"],["Film: Orka plugga – att skriva referat","https://urskola.se/Produkter/197513-Orka-plugga-Att-skriva-referat"],["Film: Källor & referatmarkörer","https://www.youtube.com/watch?v=EFueb5egwUo"]]},
"S|2026-10-13|Svenska/SVA":{desc:"Tatueraren i Auschwitz kap 1–4 med frågor",nPages:59,nSheets:2,nFilms:1,nWeeks:3,links:[["Häfte: Tatueraren i Auschwitz","https://drive.google.com/file/d/1-rI0OYFpXELqnSGKJ12DRQvKIiylalvA/view"],["Frågor till läsprojektet","https://docs.google.com/document/d/1GRzwkIFbrauJtpCKFyls3pNKL2xTeo7_9afepKvnjRQ/edit"],["Film: möte med Lale Sokolov","https://www.youtube.com/watch?v=Wz2L9vL63mI"]]},
"S|2026-10-20|Svenska/SVA":{desc:"Boksamtal kap 5–13, förberett i grupp",nPages:69,nSheets:2,nFilms:0,nWeeks:2,links:[["Uppgift: Boksamtal","https://docs.google.com/document/d/1eFVrcFceFWHP2NLn5TQR0O_sxUVcQs_G1nWWJcsmfLA/edit"],["Frågor till läsprojektet","https://docs.google.com/document/d/1GRzwkIFbrauJtpCKFyls3pNKL2xTeo7_9afepKvnjRQ/edit"]]},
"S|2026-11-24|Svenska/SVA":{desc:"Läsning kap 14–22 med skriftliga svar",nPages:64,nSheets:1,nFilms:0,nWeeks:3,links:[["Frågor till läsprojektet","https://docs.google.com/document/d/1GRzwkIFbrauJtpCKFyls3pNKL2xTeo7_9afepKvnjRQ/edit"]]},
"S|2026-11-27|Svenska/SVA":{desc:"Boken utläst, slutfrågor inspelade i grupp",nPages:63,nSheets:1,nFilms:0,nWeeks:2,links:[["Slutfrågor läsprojekt","https://docs.google.com/document/d/1GRzwkIFbrauJtpCKFyls3pNKL2xTeo7_9afepKvnjRQ/edit"]]},
"S|2026-12-04|Svenska/SVA":{desc:"Skriftlig slutuppgift om hela romanen",nPages:0,nSheets:1,nFilms:0,nWeeks:1,links:[["Slutuppgift: Tatueraren i Auschwitz","https://docs.google.com/document/d/1BcNDKaXZr0rhl2V6YPi9BQAMSKvFmLeeXVxYVmBoqes/edit"]]},
"S|2026-09-11|Franska":{desc:"Glosor kap 4b och kapitlets grammatik",nPages:2,nSheets:2,nFilms:0,nWeeks:3,links:[["Mots et révision","https://docs.google.com/document/d/1N3-sYx2EiK19g80aRIp2_kmbMqWvV5i1KjEbvEKiTbk/edit"],["Fransk grammatik (presentation)","https://docs.google.com/presentation/d/1lejfW11sPqwFEOxG0bYZggI0eKCz3hHzHz4G909jaw8/edit"]]},
"S|2026-10-02|Franska":{desc:"Passé composé, reflexiva verb, glosor kap 4b–4c",nPages:2,nSheets:3,nFilms:1,nWeeks:7,links:[["Verbes (repetition)","https://docs.google.com/document/d/1io6ERoNG3KrtW2oHJTLAKzzMCnyYL_bxRbTHRYkbo9U/edit"],["Mots et révision","https://docs.google.com/document/d/1N3-sYx2EiK19g80aRIp2_kmbMqWvV5i1KjEbvEKiTbk/edit"],["Passé composé regelbundna verb (övning)","https://wordwall.net/sv/resource/60024180/franska/pass%c3%a9-compos%c3%a9-med-avoir-regelbundna-verb"],["Passé composé oregelbundna verb (övning)","https://wordwall.net/sv/resource/60024876/franska/pass%c3%a9-compos%c3%a9-med-avoir-oregelbundna-verb"]]},
"S|2026-11-20|Franska":{desc:"Une journée typique och novellen Une histoire d'amour",nPages:6,nSheets:1,nFilms:1,nWeeks:6,links:[["Une journée typique (presentation)","https://docs.google.com/presentation/d/1qfYS2q7v2Cf7KzoMY7B_ESWdRYfP-kPzK7p-UdxrDeg/edit"],["Arbetsgång och uppgift","https://docs.google.com/document/d/1CbWkQrrPm78EfAoBkbq4dOdUkyk8-IRI_YoQGBbWQ-E/edit"],["De 560 vanligaste orden i franskan","https://docs.google.com/document/d/1tybMMAPyow0PeETnZTWzISxlHP2oAaTPcYT8xP0cAV0/edit"]]},
"S|2026-09-23|Biologi":{desc:"Genetik: DNA, mitos, meios, ärftlighet, korsningsschema",nPages:0,nSheets:2,nFilms:6,nWeeks:6,links:[["Instuderingsfrågor: cellen, DNA, gen, mitos","https://docs.google.com/document/d/1TVQMXsxtr0AIpSVJ53qUqPi-DLpr18LT_9ID7Fvwzwo/edit"],["Film: Vad är DNA och gener?","https://app.begreppa.se/videos/biologi/slaktskap-och-utveckling/vad-ar-dna-och-gener"],["Film: Ärftlighetslära","https://sliplay.se/gr/play/products/983274-arftlighetslara"],["Boken som ljudfil","https://sanomautbildning.se/Laromedel/Grundskolan-6-9/Biologi/Baslaromedel/Biologi-Direkt/Lyssna-mp3-filer/"]]},
"S|2026-11-11|Biologi":{desc:"Evolution och släktskap; material publiceras löpande",nPages:0,nSheets:0,nFilms:0,nWeeks:6,links:[["Boken som ljudfil","https://sanomautbildning.se/Laromedel/Grundskolan-6-9/Biologi/Baslaromedel/Biologi-Direkt/Lyssna-mp3-filer/"]]}
};

const D={Gustav:{cls:"8C",col:"var(--gustav)",docs:{Matematik:"https://docs.google.com/document/d/1S2oke_K6A3JULxro1KLKJBUjo3ZqLlF3R_RsVj696Bg/edit",SO:"https://docs.google.com/document/d/1ZR_GFVId9s12Wrkds-LId7iXdUuIn9gwSt3dJ0K-J5M/edit",Engelska:"https://docs.google.com/document/d/1CwkwucTKNg_jNXUD-gHH6sRTFCKUOycbNdGIeU4HLRU/edit",Bild:"https://docs.google.com/document/d/1iHL1qdhnsThI2D3U0i80nnsS0ZyWoU_D_NHhssbuLEc/edit",Textilslöjd:"https://docs.google.com/document/d/1-IcY_XZLVBo-1j8bY1jHqmELPqcJn4OFaMY3XphKpQI/edit",Franska:"https://docs.google.com/document/d/1jUhKrVH058E4-5vC_K3sC1C7c7757Jw5cwMVCk7MChw/edit",Svenska:"https://docs.google.com/document/d/1v7NhlKreegYNiDNNtVHI5QuMXc6qubX3gq3PDCIuUYo/edit",Kemi:"https://docs.google.com/document/d/1RB8R01LtKFDN8RRO8ybqGvNPNhjqRjH1proUcBb3DwM/edit",Idrott:"https://docs.google.com/document/d/1Ynk317VzzWda6vBDx_jeAWsBaL6_6aQPoi7_Cslm7KM/edit"},
teachers:{Matematik:"Marcus Jansson",SO:"Anders Lindberg",Engelska:"Maria Ödmar",Bild:"Anna Klevenås Kraft",Textilslöjd:"Anna Klevenås Kraft",Franska:"Cicci Armini",Svenska:"Therese Larsson",Kemi:"Viktor Axelsson",Idrott:"Björn Nilsson"},
ev:[
["2026-08-27","Kemi","läxa","Läsläxa: Läsbok BLÅ till s.40"],
["2026-09-03","Skolan","annat","Skolval 13:25 + föräldramöte"],
["2026-09-03","Kemi","läxa","Läsläxa: Läsbok BLÅ till s.80"],
["2026-09-04","Matematik","läxa","Läxa 1"],
["2026-09-04","Franska","läxa","Läxa kap 4a: transportmedel"],
["2026-09-07","Skolan","utvecklingssamtal","Utvecklingssamtalsdag"],
["2026-09-08","Textilslöjd","muntlig","Redovisning material"],
["2026-09-10","Svenska","inlämning","Faktatext klar"],
["2026-09-10","Kemi","läxa","Läsläxa: Läsbok BLÅ till s.120"],
["2026-09-11","Skolan","annat","Lexbyjoggen"],
["2026-09-11","Matematik","läxa","Läxa 2"],
["2026-09-17","Skolan","utvecklingssamtal","Utvecklingssamtal"],
["2026-09-17","Kemi","läxa","Läsläxa: Läsbok BLÅ till s.160"],
["2026-09-18","Matematik","läxa","Läxa 3"],
["2026-09-21","Engelska","prov","Listening test – news"],
["2026-09-22","Skolan","annat","Orienteringsdag"],
["2026-09-24","Skolan","studiedag","Studiedag"],
["2026-09-24","Kemi","läxa","Läsläxa till s.200 + öva inför prov"],
["2026-09-25","Matematik","läxa","Läxa 4"],
["2026-09-25","Franska","läxa","Läxa kap 1a: text, glosor och grammatik"],
["2026-09-28","Engelska","prov","Test: The Media"],
["2026-09-29","SO","prov","Prov: ideologier och demokratiska system"],
["2026-09-29","Svenska","inlämning","Resonerande text om språkhistoria"],
["2026-10-01","Matematik","diagnos","Diagnos kapitel 1"],
["2026-10-01","Svenska","prov","Lästest: Öva och pröva"],
["2026-10-01","Kemi","prov","Prov: organisk kemi"],
["2026-10-02","Engelska","inlämning","Dear Abbie – inlämning"],
["2026-10-02","Franska","läxa","Läxa kap 1b: text, glosor och grammatik"],
["2026-10-06","Matematik","prov","Prov: kapitel 1, tal","MA8"],
["2026-10-08","Kemi","läxa","Läsläxa till s.240"],
["2026-10-09","Matematik","läxa","Läxa 5"],
["2026-10-09","Franska","läxa","Läxa: byggnader i staden, öva inför prov"],
["2026-10-15","Kemi","läxa","Läsläxa till s.280"],
["2026-10-16","Franska","prov","Prov kapitel 1a–1b"],
["2026-10-16","Matematik","läxa","Läxa 6"],
["2026-10-19","Franska","prov","Hörförståelseprov"],
["2026-10-22","Kemi","läxa","Läsläxa till s.320"],
["2026-10-23","Matematik","läxa","Läxa 7"],
["2026-10-23","Svenska","muntlig","Muntlig uppgift: presentera din nyhet"],
["2026-10-26","Skolan","lov","Höstlov hela veckan"],
["2026-11-03","Skolan","annat","Gymnasiemässa"],
["2026-11-05","Kemi","läxa","Läsläxa: läs ut boken"],
["2026-11-06","Matematik","läxa","Läxa 8"],
["2026-11-09","Engelska","muntlig","Muntligt prov, kortfilmer"],
["2026-11-12","Matematik","diagnos","Diagnos kapitel 2"],
["2026-11-12","Kemi","prov","Prov: matens kemi"],
["2026-11-13","Franska","läxa","Devoir kapitel 2a"],
["2026-11-17","Matematik","prov","Prov: kapitel 2, procent","MA8"],
["2026-11-27","Engelska","inlämning","Final task short stories, del 1"],
["2026-11-27","Franska","prov","Prov kapitel 2a och 2c"],
["2026-11-27","Matematik","läxa","Läxa 9"],
["2026-12-01","Textilslöjd","inlämning","Inlämning slöjddokument"],
["2026-12-04","Engelska","prov","Listening test"],
["2026-12-04","Matematik","läxa","Läxa 10"],
["2026-12-07","Engelska","prov","Reading test: Robin Hood"],
["2026-12-10","Engelska","inlämning","Final task del 2: inspelad review"],
["2026-12-11","Matematik","läxa","Läxa 11"],
["2026-12-18","Skolan","annat","Julavslutning"],
["2026-12-21","Skolan","lov","Jullov, skolstart fre 8 jan"],
["2027-01-12","Matematik","diagnos","Diagnos kapitel 3 och läxa 12"],
["2027-01-13","Skolan","studiedag","Studiedag"],
["2027-01-14","Kemi","prov","Prov"],
["2027-01-18","Matematik","prov","Prov: kapitel 3, geometri","MA8"],
["2027-02-03","Skolan","utvecklingssamtal","Utvecklingssamtal"],
["2027-02-08","Engelska","muntlig","Bucket list presentations"],
["2027-02-09","Textilslöjd","muntlig","Redovisning material"],
["2027-02-15","Skolan","lov","Sportlov hela veckan"],
["2027-03-02","Skolan","studiedag","Studiedag"],
["2027-03-08","Skolan","praktik","Prao hela veckan"],
["2027-03-24","Engelska","läxa","Boken ska vara utläst"],
["2027-03-29","Skolan","lov","Påsklov hela veckan"],
["2027-05-03","Engelska","inlämning","Writing i Trelson om boken"],
["2027-05-06","Skolan","lov","Kristi himmelsfärd och klämdag"],
["2027-05-10","Engelska","prov","Reading test"],
["2027-05-11","Textilslöjd","inlämning","Inlämning slöjddokument"],
["2027-05-12","Engelska","prov","Listening test"],
["2027-06-07","Skolan","annat","Yrkesmässa åk 8"],
["2027-06-10","Skolan","annat","Skolavslutning"]]},
Syno:{cls:"9B",col:"var(--syno)",docs:{Matematik:"https://docs.google.com/document/d/1Gr9Q7SpN7vaw4OTc_4jDKtkbt6VtYwofsg9kSo5wKgA/edit",Kemi:"https://docs.google.com/document/d/1rRxgX9lMYLBHmVW63InQd_9SMYmQz6GEsEyAk_WsWkA/edit",Klass:"https://docs.google.com/document/d/1FzUOr1zGlQazk3cfXUmi9a89EID-nFl58jJdG93fYQE/edit",HKK:"https://docs.google.com/document/d/1wvVxH2Ibm_5yBx2sP23FkgPesiEMn2YDwIOnqjhmAIc/edit","Svenska/SVA":"https://docs.google.com/document/d/1oNm_1e5ZhaVO21i0hig2a3AlwggEO114zbxfi5jW4hA/edit",Franska:"https://docs.google.com/document/d/1cRuwd6ollN2EGao0HSaUCouRLjXWLoeMydj2savA6xw/edit",SO:"https://docs.google.com/document/d/1fYv1h1Y8Ww9tT5CMRQZsPaBFruR3wGpXCnfFPLRMW-w/edit",Biologi:"https://docs.google.com/document/d/1ZXr7tapcMCn2rcl1vivLK04vS3EpQHSNwZSNBu37F4A/edit",Idrott:"https://docs.google.com/document/d/1QgEWKDvqeGL9DiqUado5VsXJ9cqO_3dcu1FNu9QS-4A/edit"},
teachers:{Matematik:"Mehtap Tütüncü",Kemi:"Hanna Widlund",Klass:"Åsa Ehrenpohl och Hannah Tollesson",HKK:"Hannah Tollesson","Svenska/SVA":"Hannah Tollesson",Franska:"Cicci Armini",SO:"Sara Edman",Biologi:"Patrik Junermark",Idrott:"Martin Andersson"},
ev:[
["2026-08-24","Klass","annat","Börja söka praktikplatser"],
["2026-08-25","Klass","annat","Gymnasieinfo från SYV 10:15"],
["2026-08-26","Kemi","läxa","Kemiläxa: grundläggande begrepp"],
["2026-09-01","HKK","diagnos","Läxförhör: begrepp privatekonomi"],
["2026-09-03","SO","annat","Skolval 13:55"],
["2026-09-07","Skolan","utvecklingssamtal","Utvecklingssamtalsdag"],
["2026-09-08","HKK","diagnos","Läxförhör: försäkringar"],
["2026-09-09","Kemi","diagnos","Läxförhör: kemibegrepp"],
["2026-09-11","Skolan","annat","Lexbyjoggen"],
["2026-09-11","Franska","läxa","Läxa: kapitel 4b glosor och grammatik"],
["2026-09-15","HKK","diagnos","Läxförhör: att flytta hemifrån"],
["2026-09-15","HKK","inlämning","Recept till Budgetkocken, senast 23:59"],
["2026-09-16","Kemi","prov","Praktiskt labprov: analysmetoder"],
["2026-09-17","Skolan","utvecklingssamtal","Utvecklingssamtal"],
["2026-09-18","Svenska/SVA","inlämning","Bedömningsuppgift: sammanfattning och referat"],
["2026-09-22","Skolan","annat","Orienteringsdag"],
["2026-09-23","Biologi","prov","Prov: genetik"],
["2026-09-24","Skolan","studiedag","Studiedag och föräldramöte"],
["2026-09-25","Kemi","prov","Teoretiskt prov: atomer, joner, bindningar"],
["2026-09-28","Matematik","diagnos","Diagnos: kapitel 1, tal"],
["2026-09-29","HKK","prov","Prov: privatekonomi och konsumtion"],
["2026-10-02","Franska","prov","Prov kapitel 4b och 4c"],
["2026-10-05","Skolan","praktik","Prao hela veckan"],
["2026-10-13","Svenska/SVA","inlämning","Läsprojekt del 1, kapitel 1–4"],
["2026-10-16","Matematik","prov","Prov: kapitel 1, tal","MA9"],
["2026-10-20","Svenska/SVA","muntlig","Boksamtal: Tatueraren i Auschwitz, grupp 1"],
["2026-10-23","Svenska/SVA","muntlig","Boksamtal: Tatueraren i Auschwitz, grupp 2"],
["2026-10-26","Skolan","lov","Höstlov hela veckan"],
["2026-11-02","Svenska/SVA","inlämning","Läsprojekt del 2, kapitel 5–13"],
["2026-11-03","Skolan","annat","Gymnasiemässan"],
["2026-11-09","Skolan","annat","Teater: Cross på Backa Teatern"],
["2026-11-11","Biologi","prov","Prov: evolution"],
["2026-11-13","Kemi","prov","Prov: elektrokemi och miljö"],
["2026-11-20","Franska","prov","Prov i franska"],
["2026-11-24","Svenska/SVA","inlämning","Läsprojekt del 3, kapitel 14–22"],
["2026-11-27","Kemi","diagnos","Läxförhör: kemibegrepp"],
["2026-11-27","Svenska/SVA","inlämning","Läsprojekt del 4: boken utläst och inspelning"],
["2026-12-04","Matematik","prov","Prov: samband och förändring","MA9"],
["2026-12-04","Svenska/SVA","inlämning","Slutuppgift Tatueraren i Auschwitz"],
["2026-12-18","Skolan","annat","Julavslutning"],
["2026-12-18","Kemi","prov","Praktiskt labprov"],
["2027-01-04","Skolan","lov","Jullov måndag och tisdag"],
["2027-01-06","Skolan","studiedag","Studiedag"],
["2027-01-26","Skolan","utvecklingssamtal","Utvecklingssamtal dag 1"],
["2027-02-01","Skolan","utvecklingssamtal","Utvecklingssamtal dag 2"],
["2027-02-15","Skolan","lov","Sportlov hela veckan"],
["2027-03-02","Skolan","annat","Uppsamlingsdag"],
["2027-03-09","Skolan","studiedag","Studiedag"],
["2027-03-16","Svenska/SVA","NP","Nationellt prov svenska, delprov 1"],
["2027-03-19","Svenska/SVA","NP","Nationellt prov svenska, delprov 2"],
["2027-03-24","Skolan","annat","MA/NO-dag"],
["2027-03-26","Skolan","lov","Påsklov"],
["2027-04-13","Engelska","NP","Nationellt prov engelska"],
["2027-04-20","NO","NP","Nationellt prov NO"],
["2027-04-28","SO","NP","Nationellt prov SO, delprov 1"],
["2027-05-04","SO","NP","Nationellt prov SO, delprov 2"],
["2027-05-05","Skolan","studiedag","Studiedag"],
["2027-05-07","Skolan","lov","Lovdag"],
["2027-05-12","Matematik","NP","Nationellt prov matematik, delprov 1"],
["2027-05-14","Matematik","NP","Nationellt prov matematik, delprov 2"]]}};

const ACT=[
["Gustav","2026-08-27","17:30","Tuba ws vid pingisbordet","17:30–19:00","https://www.google.com/calendar/event?eid=MnE3MnI4ZzQ3aXVyczJlZmJyaHY0bWNlMXQgcXRxc3ZtOTBpdWFicjA5ZnZwNDF0aHU0MWNAZw"],
["Gustav","2026-09-01","20:00","Väga Gustav","20:00–21:00","https://www.google.com/calendar/event?eid=N3R1ZXBoMWFrb2JnNm1lNnNpZGd0YnRpMThfMjAyNjA5MDFUMTgwMDAwWiBxdHFzdm05MGl1YWJyMDlmdnA0MXRodTQxY0Bn"],
["Syno","2026-08-24","17:00","Planera skolarbete","17:00–18:00","https://www.google.com/calendar/event?eid=OWhzcDRsM21hanRrbzFtcmlrNDBhZzY4MTRfMjAyNjA4MjRUMTUwMDAwWiBvM3Y5YWprcmxuNXY5cnVlM3VjODZjdXM3Y0Bn"],
["Syno","2026-08-31","17:00","Planera skolarbete","17:00–18:00","https://www.google.com/calendar/event?eid=OWhzcDRsM21hanRrbzFtcmlrNDBhZzY4MTRfMjAyNjA4MzFUMTUwMDAwWiBvM3Y5YWprcmxuNXY5cnVlM3VjODZjdXM3Y0Bn"],
["Syno","2026-09-07","17:00","Planera skolarbete","17:00–18:00","https://www.google.com/calendar/event?eid=OWhzcDRsM21hanRrbzFtcmlrNDBhZzY4MTRfMjAyNjA5MDdUMTUwMDAwWiBvM3Y5YWprcmxuNXY5cnVlM3VjODZjdXM3Y0Bn"],
["Syno","2026-09-14","17:00","Planera skolarbete","17:00–18:00","https://www.google.com/calendar/event?eid=OWhzcDRsM21hanRrbzFtcmlrNDBhZzY4MTRfMjAyNjA5MTRUMTUwMDAwWiBvM3Y5YWprcmxuNXY5cnVlM3VjODZjdXM3Y0Bn"],
["Syno","2026-09-21","17:00","Planera skolarbete","17:00–18:00","https://www.google.com/calendar/event?eid=OWhzcDRsM21hanRrbzFtcmlrNDBhZzY4MTRfMjAyNjA5MjFUMTUwMDAwWiBvM3Y5YWprcmxuNXY5cnVlM3VjODZjdXM3Y0Bn"]];
function pd(s){const[y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}
function td(){const d=new Date();d.setHours(0,0,0,0);return d}
function iw(d){const t=new Date(d);t.setHours(0,0,0,0);t.setDate(t.getDate()+3-((t.getDay()+6)%7));const w1=new Date(t.getFullYear(),0,4);return 1+Math.round(((t-w1)/864e5-3+((w1.getDay()+6)%7))/7)}
function wkKey(d){const t=new Date(d);t.setDate(t.getDate()-((t.getDay()+6)%7));return t.toISOString().slice(0,10)}
